name: AZBlog Release

on:
  push:
    branches: 
      - main
    tags:
      - v*

jobs:
  build_release:    
    name: build_release
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v3              

      # Create zip-file
      - name: Generate artifact zip
        id: generate-zip
        uses: byteever/action-build-zip@master
        with:
          filename: "actions-demo.zip"        
      - name: release
        #uses: actions/create-release@v1
        uses: ncipollo/release-action@v1
        id: create_release
        #with:
        #  draft: false
        #  prerelease: false
        #  release_name: ${{ steps.version.outputs.version }}
        #  tag_name: ${{ github.ref }}
        #  body_path: CHANGELOG.md
        #env:
        #  GITHUB_TOKEN: ${{ github.token }}      
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: actions-demo.zip
          asset_name: actions-demo.zip
          asset_content_type: application/zip
