name: AZBlog Release

on:
  push:
    branches: 
      - main
    tags:
      - v*
env:
  ZIP_PATH: ./actions-demo.zip
  
jobs:
  build_release:    
    name: build_release
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v3              

      # Create zip-file
      - name: Generate artifact zip
        id: generate-zip
        uses: byteever/action-build-zip@master
        with:
          filename: ${{ env.ZIP_PATH }}
      
      # Create Github Release
      - name: release        
        uses: ncipollo/release-action@v1
        id: create_release

      # Upload Artifact
      - name: upload artifact        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}          
          asset_path: ${{ env.ZIP_PATH }}
          asset_name: ${{ env.ZIP_PATH }}
          asset_content_type: application/zip
