name: CipolloReleases

on:
  push:
    branches: 
      - main
    tags:
      - v*

jobs:
  create-artifact:
    name: Create release artifact    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate artifact zip
      uses: byteever/action-build-zip@master
      with:
        filename: "actions-demo.zip"
  release-project:
    name: Create Release    
    needs: create-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Create GitHub Release      
      uses: ncipollo/release-action@v1
      with:
        artifacts: "actions-demo.zip"
        #bodyFile: "body.md"
  
