name: Release

on:
  push:
    branches: 
      - main
    tags:
      - v*.*.*
env:
  ZIP_FILE: actions-demo.zip
  
jobs:
  build_release:    
    name: build_release
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v3              

      # Create zip-file
      - name: Generate artifact zip        
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ${{ env.ZIP_FILE }}                  
          exclusions: '*.git* /*node_modules/* .editorconfig'          
      
      # Create Github Release
      - name: release        
        uses: ncipollo/release-action@v1        
        with:
          artifacts: ${{ env.ZIP_FILE }}
          bodyFile: changelog.md
