name: Release

on:
  push:
    branches: 
      - main
    tags:
      - v*.*.*
env:
  ZIP_FILE: actions-demo.zip
  VERSION: ${GITHUB_REF#refs/*/}
  
permissions:
  contents: write
  
jobs:
  build_release:    
    if: startsWith(github.ref, 'refs/tags/')
    name: build_release
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Create zip-file
      - name: Generate artifact zip        
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ${{ env.ZIP_FILE }}                  
          exclusions: '*.git* /*node_modules/* .editorconfig'                      
       
      #- name: Create changelogs
      #  id: changelog
        #uses: heineiuo/create-changelogs@master
      #  uses: vedhavyas/generate-changelog@v4.0.2


      - name: Create Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      # Create Github Release
      - name: release                
        uses: ncipollo/release-action@v1        
        with:
          artifacts: ${{ env.ZIP_FILE }}
          body: ${{ steps.changelog.outputs.changes }}
          #body: ${{ steps.changelog.outputs.changelog }}
          #bodyFile: CHANGELOG.md          
          #generateReleaseNotes: true
