name: Release

on:
  push:
    branches: 
      - main
    tags:
      - v*.*.*
env:
  ZIP_FILE: actions-demo.zip
  VERSION: ${GITHUB_REF#refs/*/}
  
permissions:
  contents: write
  
jobs:
  build_release:    
    if: startsWith(github.ref, 'refs/tags/')
    name: build_release
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: checkout
        uses: actions/checkout@v3

      # Create zip-file
      - name: Generate artifact zip        
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ${{ env.ZIP_FILE }}                  
          exclusions: '*.git* /*node_modules/* .editorconfig'                      
       
      # Use keep-a-changelog-new-release to create a changelog file for this release
      #- name: Update changelog
      #  uses: thomaseizinger/keep-a-changelog-new-release@v1
      #  with:
      #    tag: ${{ env.VERSION }}

      #- name: Create changelogs
      #  id: changelogs
      #  uses: heineiuo/create-changelogs@master

      - name: Create changelog
        id: changelog
        uses: ryan-cha/auto-changelog-between-tags@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}        

      # Create Github Release
      - name: release                
        uses: ncipollo/release-action@v1        
        with:
          artifacts: ${{ env.ZIP_FILE }}
          #bodyFile: CHANGELOG.md
          body: ${{ steps.changelog.outputs.changelog }}
          generateReleaseNotes: true
